SET MODE MYSQL;

CREATE TABLE OAUTH_CLIENT_DETAILS(
    CLIENT_ID VARCHAR(256) PRIMARY KEY,
    RESOURCE_IDS VARCHAR(256),
    CLIENT_SECRET VARCHAR(256),
    SCOPE VARCHAR(256),
    AUTHORIZED_GRANT_TYPES VARCHAR(256),
    WEB_SERVER_REDIRECT_URI VARCHAR(256),
    AUTHORITIES VARCHAR(256),
    ACCESS_TOKEN_VALIDITY INTEGER,
    REFRESH_TOKEN_VALIDITY INTEGER,
    ADDITIONAL_INFORMATION VARCHAR(4096),
    AUTOAPPROVE VARCHAR(256)
);

CREATE TABLE OAUTH_ACCESS_TOKEN(
    AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
    TOKEN_ID VARCHAR(256),
    TOKEN LONGVARBINARY,
    USER_NAME VARCHAR(256),
    CLIENT_ID VARCHAR(256),
    AUTHENTICATION LONGVARBINARY,
    REFRESH_TOKEN VARCHAR(256)
);

CREATE TABLE OAUTH_APPROVALS(
    userId VARCHAR(256),
    clientId VARCHAR(256),
    scope VARCHAR(256),
    status VARCHAR(10),
    expiresAt TIMESTAMP,
    lastModifiedAt TIMESTAMP
);

CREATE TABLE OAUTH_REFRESH_TOKEN(
    TOKEN_ID VARCHAR(256),
    TOKEN LONGVARBINARY,
    AUTHENTICATION LONGVARBINARY
);

CREATE TABLE MEMBER (
    EMAIL VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    JOIN_FROM VARCHAR,
    PRIMARY KEY(EMAIL)
);
