INSERT INTO MEMBER (EMAIL, PASSWORD, NAME) VALUES('asd@asd', '$2a$04$N9LExXkx4sRlm./UfvvVl.KRLch8S.TTLIZMG2236kGZsam9/YmO.', 'asd');
INSERT INTO MEMBER (EMAIL, PASSWORD, NAME) VALUES('test@test', '$2a$04$N9LExXkx4sRlm./UfvvVl.KRLch8S.TTLIZMG2236kGZsam9/YmO.', 'test');
