INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, JOIN_FROM) VALUES('asd@asd', '$2a$04$N9LExXkx4sRlm./UfvvVl.KRLch8S.TTLIZMG2236kGZsam9/YmO.', 'asd', 'main');
INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, JOIN_FROM) VALUES('test@test', '$2a$04$N9LExXkx4sRlm./UfvvVl.KRLch8S.TTLIZMG2236kGZsam9/YmO.', 'test', 'main');
